eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fvsen/config-repo.git
          username: Fvsen
          password: Hq199555
          basedir: E:\SpringCloudProject\config\basedir
    bus:
      trace:
        enabled: true
      enabled: true
  #          uri: https://gitee.com/fvsen/config-repo/
#          username: fvsen
#          password: hq110168
#          basedir:  E:\SpringCloudProject\config\basedir
  rabbitmq:
#    host: 106.13.186.114
    host: 192.168.168.113
    port: 5672
    username: guest
    password: guest
#暴露/actuator/bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "*"